# Generated by Django 2.1.2 on 2018-10-10 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fluido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(default='', max_length=80)),
                ('viscosidad_cinematica', models.CharField(default='', max_length=30)),
                ('valor_viscocidad', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(default='', max_length=255)),
                ('ks', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fluido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.Fluido')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.Material')),
            ],
        ),
    ]
