# Generated by Django 2.1.2 on 2018-10-12 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(default='', max_length=4)),
                ('demanda', models.FloatField()),
                ('cota', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Tuberia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(default='', max_length=4)),
                ('longitud', models.FloatField()),
                ('diametro', models.FloatField()),
                ('start', models.CharField(default='', max_length=4)),
                ('end', models.CharField(default='', max_length=4)),
            ],
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fluido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fluidos.Fluido'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materiales.Material'),
        ),
        migrations.DeleteModel(
            name='Fluido',
        ),
        migrations.DeleteModel(
            name='Material',
        ),
        migrations.AddField(
            model_name='tuberia',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.Proyecto'),
        ),
        migrations.AddField(
            model_name='nodo',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.Proyecto'),
        ),
    ]
