# Generated by Django 2.1.2 on 2018-10-28 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0004_reservorio_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodo',
            name='x_position',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='nodo',
            name='y_position',
            field=models.IntegerField(default=0),
        ),
    ]
