# Generated by Django 2.1.2 on 2018-11-14 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0006_auto_20181028_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='tuberia',
            name='km',
            field=models.FloatField(default=0),
        ),
    ]
