# Generated by Django 2.1.2 on 2018-11-16 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0007_tuberia_km'),
    ]

    operations = [
        migrations.AddField(
            model_name='tuberia',
            name='orden',
            field=models.IntegerField(default=0),
        ),
    ]
