# Generated by Django 2.1.2 on 2018-11-19 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0008_tuberia_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodo',
            name='orden',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='tuberia',
            name='orden',
            field=models.IntegerField(default=1),
        ),
    ]
