# Generated by Django 2.1.2 on 2018-11-25 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0009_auto_20181119_0149'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiametrosGeneticos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diametro', models.FloatField()),
                ('costo', models.FloatField()),
            ],
        ),
    ]
