# Generated by Django 2.1.2 on 2018-11-25 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0010_diametrosgeneticos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DiametrosGeneticos',
        ),
    ]
