# Generated by Django 2.1.2 on 2018-11-27 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0012_diametrosgeneticos'),
    ]

    operations = [
        migrations.CreateModel(
            name='datosGeneticos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nindividuos', models.IntegerField(default=0)),
                ('npoblacion', models.IntegerField(default=0)),
                ('porcentaje_replicacion', models.IntegerField(default=0)),
                ('porcentaje_mutacion', models.IntegerField(default=0)),
                ('porcentaje_cruzami', models.IntegerField(default=0)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.Proyecto')),
            ],
        ),
    ]
