# Generated by Django 2.1.2 on 2018-11-27 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0013_datosgeneticos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosgeneticos',
            name='porcentaje_cruzami',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='datosgeneticos',
            name='porcentaje_mutacion',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='datosgeneticos',
            name='porcentaje_replicacion',
            field=models.FloatField(default=0),
        ),
    ]
