# Generated by Django 2.1.2 on 2018-12-08 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0014_auto_20181127_0058'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosgeneticos',
            name='beta',
            field=models.FloatField(default=0),
        ),
    ]
