# Generated by Django 2.1.2 on 2019-06-01 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0015_datosgeneticos_beta'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosgeneticos',
            name='pmin',
            field=models.FloatField(default=0),
        ),
    ]
