# Generated by Django 2.1.2 on 2019-06-01 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0016_datosgeneticos_pmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosgeneticos',
            name='vmin',
            field=models.FloatField(default=0),
        ),
    ]
