# Generated by Django 2.1.2 on 2019-06-17 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0017_datosgeneticos_vmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosgeneticos',
            name='arraybin',
            field=models.TextField(default=''),
        ),
    ]
