<div class="left-sidebar">
    <!-- Sidebar scroll-->
    <div class="scroll-sidebar">
        <!-- Sidebar navigation-->
        <nav class="sidebar-nav">
            <ul id="sidebarnav">
              <li class="nav-devider"></li>
                <li class="nav-label">Home</li>
                <li>
                  <a href="/">
                      <i class="fa fa-project-diagram"></i>
                      <span class="hide-menu">Proyectos</span>
                  </a>
                </li>
                <li>
                  <a href="/materiales">
                      <i class="fa fa-cube"></i>
                      <span class="hide-menu">Materiales</span>
                  </a>
                </li>
                <li>
                  <a href="/fluidos">
                      <i class="fa fa-tint"></i>
                      <span class="hide-menu">Fluidos</span>
                  </a>
                </li>
            </ul>
        </nav>
        <!-- End Sidebar navigation -->
    </div>
    <!-- End Sidebar scroll-->
</div>
