# Generated by Django 2.1.2 on 2018-10-12 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fluido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(default='', max_length=80)),
                ('viscosidad_cinematica', models.CharField(default='', max_length=30)),
                ('valor_viscocidad', models.FloatField()),
            ],
        ),
    ]
